[package]
name = "blur_algorithms"
version = "0.1.0"
authors = ["Yewo"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 3
codegen-units = 1
debug = 2